/*
SQLyog Ultimate v11.42 (64 bit)
MySQL - 10.1.10-MariaDB : Database - dbdermatix
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`dbdermatix` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `dbdermatix`;

/*Table structure for table `t_log_quiz` */

DROP TABLE IF EXISTS `t_log_quiz`;

CREATE TABLE `t_log_quiz` (
  `TID` bigint(20) NOT NULL AUTO_INCREMENT,
  `UID` varchar(100) DEFAULT NULL,
  `ANSWER` text,
  `T_TRUE` int(11) DEFAULT NULL,
  `INSERT_DATE` datetime DEFAULT NULL,
  `IP` varchar(50) DEFAULT NULL,
  `USER_AGENT` varchar(400) DEFAULT NULL,
  PRIMARY KEY (`TID`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
